# Generated by Django 4.1.2 on 2022-10-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_schadual_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schadual',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
